var S = require('./engine.js');
var pass = 0, fail = 0;
function t(name, got, want) {
  var ok = JSON.stringify(got) === JSON.stringify(want);
  if (ok) pass++; else { fail++; console.log('FAIL ' + name + ': got ' + JSON.stringify(got) + ' want ' + JSON.stringify(want)); }
}
t('risers deck 36/7', S.riserCount(36, 7), 6);
t('risers basement 108/7', S.riserCount(108, 7), 16);
t('risers garden 28/6', S.riserCount(28, 6), 5);
t('risers loft 120/8', S.riserCount(120, 8), 15);
t('risers exact division no overshoot', S.riserCount(35, 7), 5);
t('risers zero rise', S.riserCount(0, 7), 0);
t('unit rise deck', S.unitRise(36, 6), 6);
t('unit rise basement', S.unitRise(108, 16), 6.75);
t('unit rise loft', S.unitRise(120, 15), 8);
t('treads one less than risers', S.treadCount(6), 5);
t('run deck', S.totalRunIn(5, 11), 55);
t('angle deck', S.angleDeg(6, 11), 28.61);
t('angle basement', S.angleDeg(6.75, 11), 31.53);
t('angle zero tread is vertical', S.angleDeg(7, 0), 90);
t('slope deck', S.slopeIn(36, 55), 65.73);
t('buy deck 8ft', S.stringerBuyFt(65.73), 8);
t('buy tiny stair 8ft', S.stringerBuyFt(30), 8);
t('buy basement too long', S.stringerBuyFt(197.2), null);
t('throat 2x10 deck', S.throatIn('2x10', 6, 28.61), 3.98);
t('throat 2x12 deck', S.throatIn('2x12', 6, 28.61), 5.98);
t('throat unknown board null', S.throatIn('1x6', 6, 28.61), null);
t('stringers 36in at 16', S.stringerCount(36, 16), 3);
t('stringers 48in at 16', S.stringerCount(48, 16), 4);
t('stringers 60in at 16', S.stringerCount(60, 16), 5);
t('stringers min 2', S.stringerCount(10, 16), 2);
t('headroom basement', S.headroomIn(96, 12, 11, 6.75), 82.5);
t('headroom short opening fails', S.headroomIn(96, 100, 11, 6.75), 28.5);
t('geometry deck point count', S.stringerGeometry(6, 5, 6, 11, '2x10').notch.length, 12);
t('geometry deck top corner', S.stringerGeometry(6, 5, 6, 11, '2x10').notch[11], [55, 36]);
t('geometry bottom offset', S.stringerGeometry(6, 5, 6, 11, '2x10').bottom, [[5.07, -7.74], [60.07, 28.26]]);
var deck = S.compute({ totalRiseIn: 36, idealRiseIn: 7, treadDepthIn: 11, widthIn: 48, boardSize: '2x10' });
t('deck compute risers', deck.risers, 6);
t('deck compute tread boards', deck.treadBoards, 2);
t('deck compute screws', deck.screws, 40);
t('deck throat warns 2x12', deck.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('2x12 leaves 5.98') > -1; }), true);
var loft = S.compute({ totalRiseIn: 120, idealRiseIn: 8, treadDepthIn: 9, widthIn: 30, boardSize: '2x10' });
t('loft rise code bad', loft.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('7.75') > -1; }), true);
t('loft tread code bad', loft.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('10 in IRC minimum') > -1; }), true);
t('loft angle bad', loft.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('ladder territory') > -1; }), true);
t('loft throat bad', loft.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('throat') > -1; }), true);
var base = S.compute({ totalRiseIn: 108, idealRiseIn: 7, treadDepthIn: 11, widthIn: 36, boardSize: '2x12', ceilingIn: 96, openingIn: 12 });
t('basement headroom', base.headroomIn, 82.5);
t('basement headroom good', base.checks.some(function (c) { return c.level === 'good' && c.text.indexOf('clears 80') > -1; }), true);
t('basement stringer too long bad', base.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('landing') > -1; }), true);
t('basement handrail warn', base.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('handrail') > -1; }), true);
var badHead = S.compute({ totalRiseIn: 108, idealRiseIn: 7, treadDepthIn: 11, widthIn: 36, boardSize: '2x12', ceilingIn: 96, openingIn: 100 });
t('low headroom flagged', badHead.checks.some(function (c) { return c.level === 'bad' && c.text.indexOf('Headroom') > -1; }), true);
t('compute rejects zero rise', S.compute({ totalRiseIn: 0 }).error.length > 0, true);
t('garden shallow warns', S.compute({ totalRiseIn: 28, idealRiseIn: 6, treadDepthIn: 14, widthIn: 60, boardSize: '2x12' }).checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('shallow') > -1; }), true);
console.log(pass + '/' + (pass + fail) + ' tests passed');
process.exit(fail ? 1 : 0);
